### ISSUE TITLE
Bug? Default stream view is stuck on Expanded

### ISSUE THREAD

**Issue by myoriginalusername** [emonkak/feedpon#10]
When I try to change the Default stream view from Expanded to Collapsible, I get this message:
![image](https://user-images.githubusercontent.com/13319608/66708356-376f1b00-ed47-11e9-9938-7fadc19bb351.png)
This stops me from being able to hit save.

**Comment by emonkak** [comment]
Fixed in v2.0.3 df35e092dbebdc586c5428bbdbd74de2b56f8a05
