### ISSUE TITLE
Feature request: Visit website in background (open new tab without switching to it)

### ISSUE THREAD

**Issue by myoriginalusername** [emonkak/feedpon#11]
It would help if there was an option to change the visit website behaviour (`v` button on the keyboard) so that we could control whether opening the article in a tab is done in the background (`openUrlInBackground`) or not.

**Comment by emonkak** [comment]
You can do it by changing the `inBackground` parameter of "Visit website" command to `true`.

![chrome-extension___iapojifbakjkpffmeflpoaifhcifofec_index html (1)](https://user-images.githubusercontent.com/188621/66817105-25bf8a80-ef76-11e9-82ef-8631c2044665.png)
