### ISSUE TITLE
機能追加希望

### ISSUE THREAD

**Issue by hiyokosan** [emonkak/feedpon#2]
feedlyでいうところのCards Viewモードがあると便利ですね。
もう一つ、LDRにあったスクロールした記事を自動で既読にする機能があるとかなり便利です。

ご検討よろしくお願いいたします。

**Comment by emonkak** [comment]
結論から申し上げますと、どちらも導入予定はないです。
いや、この機能があった方が絶対便利なんだということでしたら、理由次第では再度導入を検討します。

以下自分の考えです。

## Cards View

まずもってFeedlyのCards Viewが読みやすいと感じないです。

理由としては、エントリ画像のサムネイル表示に否定的だからというのがあります。
サムネイルは往々にして本文とは直接関係ない、ただ見栄えを良くするだけのものであったり、関係のあるものでも本文を類推するのには役に立たないようなものが多いからです。
サムネイルはエントリのタイトルや他のどの情報よりも目立ってしまうにも関わらず、役に立つ情報を提供しないということで、ノイズになってしまうというのが自分の考えです。

サムネイル表示に否定的なので、サムネイル表示ありきのレイアウトであるCards Viewも否定的というわけです。

## スクロールした記事の自動既読

自分としてはスクロール位置で未読管理はするが、既読状態を保存するのは遷移した時のみという、今の形が最適だと考えています。
理由としては記事をスクロールしても、既読にしたくない場面があるのと、誤操作で勝手に既読になるのが嫌というのがあります。
