### ISSUE TITLE
キーボード使用時は右側が動いてくれるとうれしい

### ISSUE THREAD

**Issue by array** [emonkak/feedpon#4]
現在だと、左でなにか作業（リロード等）したあとにキーボードの「J」とか、「K」を押しても無反応なので（多分、キー入力を左のフレームが拾っている）キーボードが押されたら右側のフレームに入るようにはなると大変うれしいです。

**Comment by emonkak** [comment]
ドロップダウンとのキーイベントの競合が問題になっていてこのようになっていましたが、 efd3b2b31551a5ec567df6e7c246561b14b87cf2 で解決できました。

参考：https://stackoverflow.com/questions/24415631/reactjs-syntheticevent-stoppropagation-only-works-with-react-events

問題なければ近日中にリリースします。

**Comment by emonkak** [comment]
1.0.7としてリリースしました。
