### ISSUE TITLE
Usage of Readability API

### ISSUE THREAD

**Issue by mozfreddyb** [emonkak/feedpon#9]
Hi,

I'm working on Firefox Security and noticed that our internal use of Readability always assumes that the output of Readability is a nicely stripped readable DOM, but it never guarantees that the output of Readability is safe from Cross-Site-Scripting attacks.

This issue is to let you know that we have just updated our readme to specifically document the Threat Model. I am filing this issue because it is unclear to me whether you have a security problem. It might be worth figuring out how you use the readability output and whether you want to apply a sanitizer.

See also https://github.com/mozilla/readability/blob/master/README.md#security

**Comment by emonkak** [comment]
No problem. It have already use a sanitizing.
Thanks.
